name: th1520-build-ci

on:
  push:
    tags:        
      - '*'
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

env:
  ARCH: riscv
  CROSS_COMPILE: riscv64-linux-gnu-

jobs:
  mkrootfs:
    strategy:
      fail-fast: false

    runs-on: ubuntu-22.04

    steps:
      - name: Install Software
        run: |
              sudo apt update && \
              sudo apt install -y gdisk dosfstools build-essential \
                autoconf automake autotools-dev ninja-build make \
                libncurses-dev gawk flex bison openssl libssl-dev tree \
                gcc-riscv64-linux-gnu gfortran-riscv64-linux-gnu \
                libgomp1-riscv64-cross qemu-user-static binfmt-support \
                mmdebstrap
              wget https://mirror.iscas.ac.cn/revyos/revyos-addons/pool/main/r/revyos-keyring/revyos-keyring_2023.06.12_all.deb
              sudo apt install ./revyos-keyring_2023.06.12_all.deb

      - name: Checkout qemu
        uses: actions/checkout@v3
        with:
          repository: revyos/qemu
          path: qemu
          ref: ab8f84892a89feea60f1bb24432ff58ce6d2885c  # TODO: remove this line

      - name: build qemu
        run: |
            pushd qemu
              ./configure \
                --prefix=$HOME/qemu-install \
                --static \
                --target-list=riscv64-linux-user \
                --disable-system \
                --disable-pie \
                --interp-prefix=/etc/qemu-binfmt/%M
              make -j$(nproc)
              make install

              sudo cp -fv $HOME/qemu-install/bin/qemu-riscv64 /usr/bin/qemu-riscv64-static
            popd
            ls -al /usr/bin/qemu-riscv64-static
            sudo dpkg-reconfigure binfmt-support

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
            path: 'th1520-build'  # TODO: make this name a global variable

      - name: Make Image
        run: |
              cd th1520-build
              echo "$USER:100000:65536" > subgid
              echo "$USER:100000:65536" > subuid
              sudo cp subgid /etc/
              sudo cp subuid /etc/
              sh ./mklinux.sh
              sh ./mkrootfs.sh
              fakeroot sh ./mkimg.sh
              cd ..

      - name: Make Checksum file & Compress files
        run: |
              cd th1520-build
              sha256sum build/*.lz4 > SHA256SUMS
              cd ..

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          retention-days: 30
          name: th1520-${{ env.BUILD_ID }}
          path: |
                  th1520-build/build/SHA256SUMS
                  th1520-build/build/*.lz4

      - name: 'Create release by tag'
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
                  th1520-build/build/sha256SUMS
                  th1520-build/build/*.lz4
          token: ${{ secrets.GITHUB_TOKEN }}
